"""Demo function for aubellhop.

Provides a simple getting started demo that shows how to use bellhop
for acoustic propagation calculations.
"""

from __future__ import annotations

import pandas as pd

from .environment import Environment
from .compute import compute_arrivals


def demo() -> pd.DataFrame:
    """Run a simple bellhop demonstration and write demo file.

    This function:
    1. Creates a simple underwater acoustic environment with default settings
    2. Computes acoustic ray arrivals using bellhop
    3. Prints a summary of the arrival results to the console
    4. Writes a standalone bellhop_demo.py file to the current directory

    Returns
    -------
    results : pandas.DataFrame
        DataFrame containing the computed arrival results

    Example
    -------
    >>> import aubellhop
    >>> bellhop.demo()

    """

    # Create a simple underwater acoustic environment
    print("=" * 60)
    print("BELLHOP DEMO - Underwater Acoustic Propagation")
    print("=" * 60)
    print()

    print("Creating acoustic environment with default settings...")
    env = Environment(
        name='bellhop demo environment',
        frequency=25000,         # 25 kHz
        bottom_depth=25,                # 25 m water depth
        soundspeed=1500,         # 1500 m/s constant sound speed
        source_depth=5,          # source at 5 m depth
        receiver_depth=10,       # receiver at 10 m depth
        receiver_range=1000,     # 1 km range
        bottom_soundspeed=1600,  # seabed sound speed
        bottom_density=1600      # seabed density
    )

    print(f"  Frequency: {env.frequency} Hz")
    print(f"  Water depth: {env.bottom_depth} m")
    print(f"  Sound speed: {env.soundspeed} m/s")
    print(f"  Source depth: {env.source_depth} m")
    print(f"  Receiver depth: {env.receiver_depth} m")
    print(f"  Receiver range: {env.receiver_range} m")
    print()

    # Compute arrivals
    print("Computing acoustic ray arrivals...")
    results = compute_arrivals(env)

    # Print summary of results
    print()
    print("=" * 60)
    print("ARRIVAL RESULTS")
    print("=" * 60)

    if "time_of_arrival" in results.columns:
        arrivals = results["time_of_arrival"]
        num_arrivals = len(arrivals)

        print(f"Number of arrivals: {num_arrivals}")
        print()

        if num_arrivals > 0:
            # Convert to list to ensure consistent indexing (pandas Series)
            arrival_times = list(arrivals)
            print(f"First arrival time: {arrival_times[0]:.6f} seconds")
            print(f"Last arrival time: {arrival_times[-1]:.6f} seconds")
            print()

            # Show first few arrivals
            n_show = min(5, num_arrivals)
            print(f"First {n_show} arrival times (seconds):")
            for i in range(n_show):
                print(f"  Arrival {i+1}: {arrival_times[i]:.6f} s")

            if num_arrivals > n_show:
                print(f"  ... ({num_arrivals - n_show} more arrivals)")
    else:
        print("No arrivals computed.")

    print()
    print("=" * 60)

    # Write demo file
    demo_filename = "bellhop_demo.py"
    print(f"Writing demo script to: {demo_filename}")

    demo_code = '''#!/usr/bin/env python3
"""BELLHOP Demo Script

This script demonstrates basic usage of the bellhop underwater acoustic
propagation model. It creates a simple acoustic environment and computes
acoustic ray arrivals between a source and receiver.

Generated by: bellhop.demo()
"""

import aubellhop as bh

# Create acoustic environment
env = bh.Environment(
    name='bellhop demo environment',
    frequency=25000,         # 25 kHz
    bottom_depth=25,                # 25 m water depth
    soundspeed=1500,         # 1500 m/s constant sound speed
    source_depth=5,          # source at 5 m depth
    receiver_depth=10,       # receiver at 10 m depth
    receiver_range=1000,     # 1 km range
    bottom_soundspeed=1600,  # seabed sound speed
    bottom_density=1600      # seabed density
)

print("Environment configuration:")
print(f"  Frequency: {env.frequency} Hz")
print(f"  Water depth: {env.bottom_depth} m")
print(f"  Sound speed: {env.soundspeed} m/s")
print(f"  Source depth: {env.source_depth} m")
print(f"  Receiver depth: {env.receiver_depth} m")
print(f"  Receiver range: {env.receiver_range} m")
print()

# Compute acoustic arrivals
print("Computing acoustic ray arrivals...")
results = bh.compute_arrivals(env)

# Display results
if "time_of_arrival" in results.columns:
    arrivals = results["time_of_arrival"]
    print(f"\\nNumber of arrivals: {len(arrivals)}")

    if len(arrivals) > 0:
        # Convert to list to ensure consistent indexing
        arrival_times = list(arrivals)
        print(f"First arrival time: {arrival_times[0]:.6f} seconds")
        print(f"Last arrival time: {arrival_times[-1]:.6f} seconds")

        # Show first few arrivals
        n_show = min(5, len(arrivals))
        print(f"\\nFirst {n_show} arrival times (seconds):")
        for i in range(n_show):
            print(f"  Arrival {i+1}: {arrival_times[i]:.6f} s")

        if len(arrivals) > n_show:
            print(f"  ... ({len(arrivals) - n_show} more arrivals)")
else:
    print("No arrivals computed.")

print("\\nDemo complete!")
'''

    with open(demo_filename, 'w') as f:
        f.write(demo_code)

    print("Demo script written successfully!")
    print()
    print("To run the demo script again:")
    print(f"  python3 {demo_filename}")
    print()
    print("=" * 60)

    return results
