
####### PROJECT #######

[project]
name = "aubellhop"
dynamic = ["version"]

description = "Bellhop underwater acoustic propagation model"
readme = "README.md"
license = "GPL-3.0-or-later"

dependencies = [
    "matplotlib",
    "numpy",
    "scipy",
    "pandas",
    "bokeh",
]

requires-python = ">=3.12, <3.15"

authors = [
  {name = "Will Robertson", email = "wspr81@gmail.com"},
]
maintainers = [
  {name = "Will Robertson", email = "wspr81@gmail.com"},
]

classifiers = [
  "Development Status :: 4 - Beta", #   5 - Production/Stable
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]

[project.urls]
Homepage = "https://github.com/avc-adelaide/aubellhop"
Documentation = "https://avc-adelaide.github.io/aubellhop/"
Repository = "https://github.com/avc-adelaide/aubellhop.git"
Issues = "https://github.com/avc-adelaide/aubellhop/issues"
Changelog = "https://github.com/avc-adelaide/aubellhop/blob/master/CHANGES.md"

[project.optional-dependencies]
dev = [
    "pytest",
    "gcovr",
    "ruff",
    "coverage",
    "jupyter",
    "nbformat",
    "sphinx",
    "sphinxcontrib-mermaid",
    "quarto>=0.1.0",
    "fortitude-lint>=0.8",
]


####### BUILD #######

[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "python/aubellhop/_version.py"


####### SETUPTOOLS #######

[tool.setuptools]
py-modules = []

[tool.setuptools.packages.find]
where = ["python"]
include = ["aubellhop*"]
namespaces = false

[tool.setuptools.package-data]
aubellhop = ["bin/*"]


####### RUFF #######

[tool.ruff]
output-format = "github"


####### COVERAGE #######

[tool.coverage.run]
source = ["python/aubellhop"]
omit = [
    "*/tests/*",
    "*/test_*",
    "*/__pycache__/*",
]

[tool.coverage.report]
show_missing = true
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "class .*\\bProtocol\\):",
    "@(abc\\.)?abstractmethod",
]

[tool.coverage.html]
directory = "_coverage_python"

