project:
  type: website
  output-dir: ../_build/media/quarto

website:
  title: "Bellhop Tutorials"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: intro.qmd
        text: Introduction
      - href: compute.qmd
        text: Compute Tasks
      - href: environ.qmd
        text: Environments
      - href: ssp.qmd
        text: Soundspeeds
      - href: surface.qmd
        text: Surfaces

format:
  html:
    toc: true
    toc-depth: 3
    toc-title: "Contents"
    toc-location: left
    number-sections: true
