project:
  type: website
  output-dir: ../_build/media/quarto

website:
  title: "Bellhop Tutorials"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: intro.qmd
        text: Intro
      - href: ssp.qmd
        text: Soundspeed
      - href: surface.qmd
        text: Surface

format:
  html:
    toc: true
    toc-depth: 3
    toc-title: "Contents"
    toc-location: left
    number-sections: true
