# TOML allows comments, which is handy

[extra.ford]
project = "The BELLHOP underwater acoustics ray tracing tool"
author = "Michael B. Porter / UC San Diego / Adelaide University"
version = "2025-08-25"
license = "gpl"
summary = '''
  BELLHOP is an underwater acoustic simulator that uses beam/ray tracing
  to model acoustic wave propagation in ocean environments. It is part of
  the Acoustics Toolbox and provides both 2D and 3D acoustic modeling capabilities.
'''

src_dir = ["../fortran"]
media_dir = "static"
output_dir = "_build"
page_dir = "pages"

preprocessor = "gfortran -E"
project_github = "https://github.com/avc-adelaide/bellhoppe"
github = "https://github.com/avc-adelaide/bellhoppe"

source = true
graph = true
search = false
